import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  const strains = [
    {
      name: 'Ditch Weed',
      drugType: 'marijuana',
      growTimeMinutes: 5,
      baseValue: 5,
      baseYield: 1,
      difficulty: 1,
      unlockLevel: 1,
      description: 'La cepa mas basica. Crece en cualquier lado. Ideal para empezar.',
      specialTrait: '',
      idealWater: 55,
      idealLight: 60,
      idealNutrients: 50,
      seedCost: 2,
      icon: '🌱',
      color: '#65a30d',
      volatility: 0.4,
    },
    {
      name: 'Skunk #1',
      drugType: 'marijuana',
      growTimeMinutes: 10,
      baseValue: 10,
      baseYield: 2,
      difficulty: 2,
      unlockLevel: 2,
      description: 'Clasica cepa con alto rendimiento. Olor intenso pero grandes cogollos.',
      specialTrait: '',
      idealWater: 60,
      idealLight: 65,
      idealNutrients: 60,
      seedCost: 8,
      icon: '🦨',
      color: '#84cc16',
      volatility: 0.5,
    },
    {
      name: 'Purple Haze',
      drugType: 'marijuana',
      growTimeMinutes: 15,
      baseValue: 16,
      baseYield: 3,
      difficulty: 4,
      unlockLevel: 5,
      description: 'Cepa psicodelica con tonos morados. Buena relacion calidad-precio.',
      specialTrait: '',
      idealWater: 70,
      idealLight: 75,
      idealNutrients: 70,
      seedCost: 18,
      icon: '💜',
      color: '#a855f7',
      volatility: 0.5,
    },
    {
      name: 'Northern Lights',
      drugType: 'marijuana',
      growTimeMinutes: 30,
      baseValue: 35,
      baseYield: 4,
      difficulty: 6,
      unlockLevel: 8,
      description: 'Leyenda indoor. Resinosa y potente. Perfecta para cultivo avanzado.',
      specialTrait: '',
      idealWater: 75,
      idealLight: 80,
      idealNutrients: 75,
      seedCost: 55,
      icon: '🌌',
      color: '#818cf8',
      volatility: 0.7,
    },
    {
      name: 'OG Kush',
      drugType: 'marijuana',
      growTimeMinutes: 60,
      baseValue: 100,
      baseYield: 4,
      difficulty: 10,
      unlockLevel: 12,
      description: 'La reina de la costa oeste. Alta exigencia pero gran recompensa.',
      specialTrait: '',
      idealWater: 80,
      idealLight: 85,
      idealNutrients: 80,
      seedCost: 150,
      icon: '👑',
      color: '#f59e0b',
      volatility: 0.7,
    },
    {
      name: 'White Widow',
      drugType: 'marijuana',
      growTimeMinutes: 100,
      baseValue: 200,
      baseYield: 5,
      difficulty: 15,
      unlockLevel: 18,
      description: 'Cubierta de cristales blancos. Solo para cultivadores expertos.',
      specialTrait: '',
      idealWater: 85,
      idealLight: 90,
      idealNutrients: 85,
      seedCost: 400,
      icon: '👻',
      color: '#e2e8f0',
      volatility: 0.8,
    },
    {
      name: 'Girl Scout Cookies',
      drugType: 'marijuana',
      growTimeMinutes: 200,
      baseValue: 500,
      baseYield: 6,
      difficulty: 25,
      unlockLevel: 25,
      description: 'La cepa legendaria. Cultivo extremadamente dificil pero produce los cogollos mas valiosos.',
      specialTrait: '',
      idealWater: 90,
      idealLight: 95,
      idealNutrients: 90,
      seedCost: 1200,
      icon: '🍪',
      color: '#fbbf24',
      volatility: 0.9,
    },
    {
      name: 'Jack Herer',
      drugType: 'marijuana',
      growTimeMinutes: 300,
      baseValue: 1000,
      baseYield: 7,
      difficulty: 35,
      unlockLevel: 35,
      description: 'La leyenda del activismo. Estimulante y productiva. Solo para cultivadores de elite.',
      specialTrait: '',
      idealWater: 88,
      idealLight: 92,
      idealNutrients: 87,
      seedCost: 2800,
      icon: '🏆',
      color: '#f59e0b',
      volatility: 1.0,
    },
    {
      name: 'Amnesia Haze',
      drugType: 'marijuana',
      growTimeMinutes: 420,
      baseValue: 2000,
      baseYield: 8,
      difficulty: 50,
      unlockLevel: 50,
      description: 'Potencia cerebral extrema. Su valor en el mercado es descomunal.',
      specialTrait: '',
      idealWater: 90,
      idealLight: 94,
      idealNutrients: 90,
      seedCost: 6400,
      icon: '🧠',
      color: '#818cf8',
      volatility: 1.1,
    },
    {
      name: 'Blue Dream',
      drugType: 'marijuana',
      growTimeMinutes: 600,
      baseValue: 5000,
      baseYield: 9,
      difficulty: 70,
      unlockLevel: 70,
      description: 'La reina de la costa oeste. Equilibrio perfecto entre cantidad y calidad.',
      specialTrait: '',
      idealWater: 93,
      idealLight: 96,
      idealNutrients: 93,
      seedCost: 18000,
      icon: '💤',
      color: '#38bdf8',
      volatility: 1.3,
    },
    {
      name: "God's Gift",
      drugType: 'marijuana',
      growTimeMinutes: 900,
      baseValue: 15000,
      baseYield: 10,
      difficulty: 100,
      unlockLevel: 100,
      description: 'La cepa definitiva. Solo los verdaderos emperadores pueden permitirse cultivarla.',
      specialTrait: '',
      idealWater: 95,
      idealLight: 98,
      idealNutrients: 95,
      seedCost: 60000,
      icon: '✨',
      color: '#fbbf24',
      volatility: 1.5,
    },
  ];

  for (const strain of strains) {
    const { volatility, ...strainData } = strain;
    const existing = await prisma.strain.findUnique({ where: { name: strain.name } });
    if (!existing) {
      const created = await prisma.strain.create({ data: strainData });
      await prisma.marketPrice.create({
        data: {
          strainId: created.id,
          currentPrice: strain.baseValue,
          basePrice: strain.baseValue,
          volatility,
          trend: 'stable',
          changePercent: 0,
        },
      });
      console.log('Created strain:', strain.name, `(vol: ${volatility})`);
    }
  }

  console.log('Seed complete!');
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
